### ISSUE TITLE
Rename the repository and crate

### ISSUE THREAD

**Issue by golangdojo99** [EdJoPaTo/tui-rs-tree-widget#13]
Numerous third-party widgets (`tui-logger`, `tui-textarea`, etc.) for `tui-rs` are named in `tui-*` format (do not include widget as suffix). For the sake of consistency, you should rename `tui-rs-tree-widget` to similar format (`tui-tree` or `tui-treeview` if you prefer GTK names for widgets) as well.

**Comment by EdJoPaTo** [comment]
As crates.io is immutable and the names of crates are unique and can not be deleted / renamed I am not sure if renaming it is that helpful. Its also not as easy for users to notice/find the new name of a crate when they are already using the old one.

So yeah, for consistency I think you are right, going with a certain name style might be a good idea but as crates can not be renamed without much hazzle I dont think renaming it would be a good idea.

That is if I am not overlooking something?

**Comment by EdJoPaTo** [comment]
as this is migrated into ratatui (see #18) this issue can be closed in my opinion
