### ISSUE TITLE
Index out of bounds with `key_down` and `key_up`

### ISSUE THREAD

**Issue by dzfrias** [EdJoPaTo/tui-rs-tree-widget#15]
When no tree items are passed into the `key_down` or `key_up` methods, there is a panic. From a UI standpoint, I personally feel like this doesn't make sense. I'm not sure if this was intentional or not, but let me know if you want me to submit a PR to change this behavior!

**Comment by EdJoPaTo** [comment]
Oh, no this is not intentional. Would you like to create a Pull Request? Otherwise I can also fix this myself. Thank you for the report!

**Comment by dzfrias** [comment]
Ok, sounds good! I created a Pull Request
