### ISSUE TITLE
Migrate from tui to ratatui

### ISSUE THREAD

**Issue by dzfrias** [EdJoPaTo/tui-rs-tree-widget#18]
With the recent release of [ratatui](https://github.com/tui-rs-revival/ratatui), the tui-rs revival project, I think it would be best to support the new version to help people convert over.

[ansi-to-tui](https://github.com/uttarayan21/ansi-to-tui) has an ongoing [PR](https://github.com/uttarayan21/ansi-to-tui/pull/23) for it right now, and I think it would be good to do the same.

**Comment by EdJoPaTo** [comment]
An alternative idea might be to integrate this widget into ratatui 🤔

**Comment by dzfrias** [comment]
To resist this idea, I can open an issue in `ratatui`. It shouldn't be too hard to migrate over to use `ratatui` either way.

**Comment by EdJoPaTo** [comment]
> I can open an issue in `ratatui`

Feel free to do so (any maybe link to this issue)!

> It shouldn't be too hard to migrate over to use `ratatui` either way.

I'm not totally sure how well that would work as there also is the Flatten / Identifier Logic which is kinda specific. I would like a more generic approach if its going to be merged but I don't really know how that should be looking.

**Comment by dzfrias** [comment]
Hmmm yeah. I can look at some of the existing `ratatui` widgets and see if anything would be better to use if the merge goes through.

**Comment by EdJoPaTo** [comment]
The current plan is to integrate tui-rs-tree-widget into ratatui.
I think a good idea is to finish the planned tasks (like #19) before creating a PR adding this widget to ratatui.

Just as a headsup: I dont have that much time currently but I want to bring this forward as I think this is the right way forward.

**Comment by deifactor** [comment]
In the meantime, would you accept a PR that updates this to use ratatui so it can be used right now?

**Comment by EdJoPaTo** [comment]
> In the meantime, would you accept a PR that updates this to use ratatui so it can be used right now?

I am not entirely sure about it… the ideal solution would be to have it embedded in ratatui…
Releasing a new version for ratatui is probably fine as tui users can still use the older version? The downside is that when its moved into ratatui the crate is only relevant for tui users which would then need to use an "old" version for that…

Maybe a new version with two features, tui and ratatui where tui is the default feature? Not sure if that works?

**Comment by deifactor** [comment]
[tui-textarea](https://github.com/rhysd/tui-textarea) supports both using something equivalent to

```rs
#[cfg(feature = "ratatui")]
use ratatui as tui;
#[cfg(not(feature = "ratatui"))]
#[allow(clippy::single_component_path_imports)]
use tui;
```

in `src/lib.rs`, and then other modules can refer to `crate::tui` to pick up the right one.
