### ISSUE TITLE
Add getter for Item::Identifier

### ISSUE THREAD

**Issue by thscharler** [EdJoPaTo/tui-rs-tree-widget#30]
I would like to create a copy of the tree without text, style etc to keep it around in the state.
Keeping it in the state seems necessary for later navigation, but as far as I've seen the
navigation code only ever uses the Identifier.  So getting access to the identifier would
suffice. 

With that I could create a Item<'static> to circumvent a tick infestation for my state. 

I could make the PR, no problem.

**Comment by EdJoPaTo** [comment]
Caching the last structure happens with 4ea480016d4ff4c1c1d03b96f5fe2d8949a0b5e9 now (not released yet). It simplifies the usage a lot which is neat!

A getter for the identifier… not sure how useful that would be as the identifier is "only" for the current level. `Vec<Identifier>` identifies something in the whole tree which has to be constructed then manually :thinking:

**Comment by thscharler** [comment]
Nice!
I only skimmed over the diff today, and I'm currently quite busy with other things.
Will look at it some time next week.

**Comment by thscharler** [comment]
Ok, I was curious and tried it.

It works, almost. If I press Left at the top level of the tree the selection is lost completely.

And btw, why did you remove flatten(). I really liked that one.

**Comment by EdJoPaTo** [comment]
> If I press Left at the top level of the tree the selection is lost completely.

That's the same behavior as before.

> And btw, why did you remove flatten(). I really liked that one.

Performance improvements of render that changed the Flattened type so I moved it to private to change it more easily without breaking. `mqttui` used it for total height calculation so I added that as its own function (which is also more performant now): `TreeState::total_required_height`.

Other needs could also be added as more effective methods… Would need to look closer on your code to see what should be added to get whats needed.

**Comment by thscharler** [comment]
What would be great is a list of Rect for all the rendered tree items.

This could come out as a side effect of rendering.
It would help with mouse interaction too.

**Comment by EdJoPaTo** [comment]
> It would help with mouse interaction too.

https://github.com/EdJoPaTo/mqttui/blob/27dca3f099d6cb057870eefd31217703f232e207/src/interactive/details/payload_view.rs#L43-L48

Maybe something like this could be integrated into TreeState? But mqttui can only do this as it knows the item height is always 1 so it can not be integrated this way directly :thinking: 

An alternative might be to keep the index / screen offset of last render to handle this. So instead of your suggestion of getting that list of rendered Rects keep that inside TreeState for that purpose.

**Comment by thscharler** [comment]
A list of the rects would be sufficient. I could use the index into this list with
`TreeState::select_visible_index()` which would do the thing. 

Or otherwise something like `TreeState::select_item_at(column, row)` would be ok too.

Depending on the fact that items are only 1 row high seems a bit limiting.

**Comment by EdJoPaTo** [comment]
Given that `mqttui` toggles when an item is already selected and returning the identifier at the position requires cloning the identifier, I merged that into a single function click_at.

The only thing that comes to mind that would need the actual identifier below a mouse curser would update the GUI based on hover… not sure how useful that would be for terminal applications.

**Comment by EdJoPaTo** [comment]
> > And btw, why did you remove flatten(). I really liked that one.
> 
> Performance improvements of render that changed the Flattened type so I moved it to private to change it more easily without breaking. `mqttui` used it for total height calculation so I added that as its own function (which is also more performant now): `TreeState::total_required_height`.

Also, flatten will have a comeback as `get_nodes` with the `TreeData` trait (#34).

> See what I could do with that alone:
> https://github.com/thscharler/rat-scroll/blob/master/src/adapter/tree.rs

Commented out completely :upside_down_face:

**Comment by EdJoPaTo** [comment]
Side note: #38 added the original requested `Item::identifier` method. Given that #34 takes more advantage of them it's a good thing to have them more easily accessible.
Thanks for bringing it up and ending up providing ideas for simplifying the mouse handling stuff too :sparkles:

**Comment by thscharler** [comment]
You're welcome! :)
