### ISSUE TITLE
Change items to reference

### ISSUE THREAD

**Issue by fioncat** [EdJoPaTo/tui-rs-tree-widget#35]
Now, everytime we create a `TreeWidget`, the whole `items` needs to be cloned:

```rust
TreeWidget::new(items.clone())
```

If the items are very large, this will consume a lot of CPU and memory during each render process.

TreeWidget does not change items. Could you consider changing the items type to reference, or at least use Cow?

**Comment by EdJoPaTo** [comment]
The idea of the `TreeItem` is to be a thin wrapper. Like the Tree, generated on each render, keeping a reference to the original data. The original data should be persisted. At least thats the idea so far.

With the `TreeData` (#34) I am currently working on a reference will be used and whatever implements that trait will be called on each render, so given the items as reference would be possible then.

**Comment by fioncat** [comment]
Thank you! The trait can indeed achieve my needs, I look forward to it being implemented.
