### ISSUE TITLE
tui version bump

### ISSUE THREAD

**Issue by tramhao** [EdJoPaTo/tui-rs-tree-widget#6]
Would you please upgrade the tree widget to work with tui 0.16? I'm using tuirealm-tree-widget, which is a wrapper of tui-rs-tree-widget. Thanks.

**Comment by EdJoPaTo** [comment]
see https://github.com/veeso/tui-realm-treeview/issues/5#issuecomment-897499433

Thanks @tramhao for letting me know my crate is used in another library out there :sparkles:
